// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zygpfaxvxrqnfjfxmziw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Z3BmYXh2eHJxbmZqZnhteml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTIyNjYsImV4cCI6MjA3MDk2ODI2Nn0.CLMrJlomegvSQ3awItLeRlM6xQLrDFAkzmxX74EyLFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});